site_name: Mapzen Javascript SDK
docs_dir: src-mapzen-js
site_dir: dist-mapzen-js

pages:
  - Home: index.md
  - 'Getting started': 'gettingstarted.md'
  - 'API': 'api.md'

extra:
  site_subtitle: 'A thin wrapper that packages up everything you need to use Mapzen services in your web applications.'
  project_repo_url: https://github.com/mapzen/mapzen.js
  docs_base_url: https://github.com/mapzen/mapzen-js/tree/kkowalsky-text-edit/docs
