site_name: Time-Distance Matrix
docs_dir: src-matrix
site_dir: dist-matrix

pages:
  - Home: nothing.md

redirects:
  '.': '/documentation/mobility/matrix/api-reference'
  'api-reference': '/documentation/mobility/matrix/api-reference'

extra:
  site_subtitle: 'Calculate the time and distance between a set of locations.'
  #'Time-distance matrix service'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/master/matrix
