site_name: Metro Extracts
docs_dir: src-metro-extracts
site_dir: dist-metro-extracts
include_next_prev: false # next/prev is in alpha order; we don't want this

pages:
  - Home: index.md
  - 'Tutorial': 'tutorial.md'
  - 'Custom extracts': 'custom-extracts.md'
  - 'File formats': 'file-format.md'

mz:redirects:
  'overview': '.'
  'walkthrough': 'tutorial'

extra:
  site_subtitle: Download city-sized portions of OpenStreetMap data in a variety of formats.
  project_repo_url: https://github.com/mapzen/metro-extracts
  docs_base_url: https://github.com/mapzen/metro-extracts/tree/master/docs
  exclude_home_contents_in_toc: false
