site_name: Metro Extracts
repo_url: https://github.com/mapzen/mapzen-docs
remote_branch: master
google_analytics: ['UA-47035811-1', 'mapzen.com']
docs_dir: src/metro-extracts
theme: mkdocs
theme_dir: theme
site_dir: dist/metro-extracts
include_nav: true
include_next_prev: false # next/prev is in alpha order; we don't want this

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: true

markdown_extensions:
  - smarty
  - toc:
      permalink: ' ' # Blank space; this marker is styled in CSS.
  - sane_lists
  - nl2br
  - outline
  - codehilite
  # Set of PyMdown extensions to flesh out GFM-mimicry
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.githubemoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# Extra variables for templates
extra:
  site_subtitle: Download city-sized portions of OpenStreetMap data in a variety of formats.
  project_repo_url: https://github.com/mapzen/metroextractor-cities
  docs_base_url: https://github.com/mapzen/mapzen-docs/tree/master/metro-extracts
  display_project_name_api_key: false
