site_name: Metro Extracts
repo_url: https://github.com/mapzen/metroextractor-cities
remote_branch: master
google_analytics: ['UA-47035811-1', 'mapzen.com']
docs_dir: src/metro-extracts
theme: mkdocs
theme_dir: theme
site_dir: dist/metro-extracts
include_nav: true
include_next_prev: false # next/prev is in alpha order; we don't want this
extra_javascript:
  - js/bootstrap.min.js # Copied latest version of Bootstrap

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: true

markdown_extensions:
  - smarty
  - toc:
      permalink: ' ' # Blank space; this marker is styled in CSS.
  - sane_lists

# Extra variables for templates
extra:
  docs_repo_url: https://github.com/mapzen/mapzen-docs
  display_project_name_api_key: false
