site_name: Mapzen Mobility
docs_dir: src-mobility
site_dir: dist-mobility

mz:renames:
  'optimized_route/api-reference.md': 'optimized/api-reference.md'
  'api-reference.md': 'turn-by-turn/api-reference.md'
  'add-routing-to-a-map.md': 'turn-by-turn/add-routing-to-a-map.md'

pages:
  - Home: index.md
  - 'Terminology': 'terminology.md'
  - Turn-by-Turn:
    - 'API reference': 'turn-by-turn/api-reference.md'
    - 'Add Mapzen Turn-by-Turn routing to a map': 'turn-by-turn/add-routing-to-a-map.md'
  - 'Optimized route': 'optimized/api-reference.md'
  - 'Time-Distance Matrix': 'matrix/api-reference.md'
  - 'Decode a route shape': 'decoding.md'
  - 'Release notes': 'release-notes.md'

extra:
  site_subtitle: 'Add routing and navigation to your web and mobile apps.'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/master
