site_name: Mapzen Mobility
docs_dir: src-mobility
site_dir: dist-mobility

pages:
  - Home: index.md
  - 'Terminology': 'terminology.md'
  - Turn-by-Turn:
    - 'API reference': 'api-reference.md'
    - 'Add Mapzen Turn-by-Turn routing to a map': 'add-routing-to-a-map.md'
  - 'Optimized route': 'optimized_route/api-reference.md'
  - 'Time-Distance Matrix': 'matrix/api-reference.md'
  - 'Decode a route shape': 'decoding.md'
  - 'Release notes': 'release-notes.md'

redirects:
  'turn-by-turn': 'mobility'
  'optimized': 'mobility/optimized'
  'matrix': 'mobility/matrix'

extra:
  site_subtitle: 'Add routing and navigation to your web and mobile apps.'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/master
