site_name: Optimized Route
docs_dir: src-optimized
site_dir: dist-optimized
include_next_prev: false
extra_css: [css/codehilite/mapzen.css]

pages:
  - Home: nothing.md

redirects:
  '.': '/documentation/mobility/optimized-route/api-reference'
  'api-reference': '/documentation/mobility/optimized-route/api-reference'

extra:
  site_subtitle: 'Find the most efficient route between many locations.'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/master/optimized_route
