site_name: Developer overview
docs_dir: src-overview
site_dir: dist-overview
include_next_prev: false # next/prev is in alpha order; we don't want this

pages:
  - Overview: index.md

extra:
  site_subtitle: Get started developing with Mapzen's products
  project_repo_url: https://github.com/mapzen/mapzen-docs-generator
  docs_base_url: https://github.com/mapzen/mapzen-docs-generator/tree/master/docs
  exclude_home_contents_in_toc: false
