site_name: Tangram
docs_dir: src-tangram
site_dir: dist-tangram

# Because Tangram does not organize documentation in folders, we're going to have
# to enforce the Table of Contents structure manually in the configuration below.
# This means pages should be added or subtracted manually here if the files change.
pages:
  - Home: index.md
  - Concept Overviews:
    - 'The Scene File': 'Scene-file.md'
    - 'Data Filters': 'Filters-Overview.md'
    - 'Styles': 'Styles-Overview.md'
    - 'Shaders': 'Shaders-Overview.md'
    - 'Raster Sources': 'Raster-Overview.md'
    - 'Lights': 'Lights-Overview.md'
    - 'Cameras': 'Cameras-Overview.md'
    - 'Materials': 'Materials-Overview.md'
    - 'YAML': 'yaml.md'
  - Syntax Reference:
    - 'cameras': 'cameras.md'
    - 'draw': 'draw.md'
    - 'global': 'global.md'
    - 'import': 'import.md'
    - 'layers': 'layers.md'
    - 'lights': 'lights.md'
    - 'materials': 'materials.md'
    - 'scene': 'scene.md'
    - 'shaders': 'shaders.md'
    - 'sources': 'sources.md'
    - 'styles': 'styles.md'
    - 'textures': 'textures.md'
  - JavaScript API: 'Javascript-API.md'
  - Android API: 'Android-API.md'
  - Demos & Examples:
    - 'Demos': 'Demos.md'
  - Tutorials:
    - 'Introduction': 'tutorials/Tutorials.md'
    - 'JS Walkthrough': 'walkthrough.md'
    - 'JS Quickstart': 'tutorials/JSquickstart.md'
    - 'Android Walkthrough': 'android-walkthrough.md'
    - 'Importing Styles': 'tutorials/imports.md'
    - 'Leaflet Layers': 'tutorials/layers.md'
    - 'Custom Data': 'tutorials/custom-data.md'
    - 'Styling': 'tutorials/styling.md'
    - 'Custom Graphics': 'tutorials/graphics.md'
    - 'Shaders': 'tutorials/shaders.md'
    - 'Advanced Styling': 'tutorials/advanced-styling.md'
    - 'Data Visualization': 'tutorials/data-visualization.md'
    - 'Advanced Shaders': 'tutorials/advanced-shaders.md'
    - 'Tips': 'tutorials/tips.md'

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set
# to true to halt processing when a broken link is found, false prints a warning.
strict: false

# Extra variables for templates
extra:
  site_subtitle: Render 2D and 3D maps with fine control over almost every aspect of the map-making process.
  project_repo_url: https://github.com/tangrams/tangram
  docs_base_url: https://github.com/tangrams/tangram-docs/tree/gh-pages/pages
