site_name: Mapzen Turn-by-Turn
docs_dir: src/turn-by-turn
site_dir: dist/turn-by-turn

pages:
  - Home: index.md
  - 'API reference': 'api-reference.md'
  - 'Terminology': 'terminology.md'
  - 'Add Mapzen Turn-by-Turn routing to a map': 'add-routing-to-a-map.md'
  - 'Decode a route shape': 'decoding.md'

extra:
  site_subtitle: 'Add routing and navigation to your web and mobile apps.'
  project_repo_url: https://github.com/valhalla/
  docs_base_url: https://github.com/valhalla/valhalla-docs/tree/master
