site_name: Vector Tile Service
docs_dir: src/vector-tiles
site_dir: dist/vector-tiles

pages:
  - Home: docs/index.md
  - 'Get started': 'docs/use-service.md'
  - 'Make a map': 'docs/display-tiles.md'
  - 'API keys and rate limits': 'docs/api-keys-and-rate-limits.md'
  - 'Attribution': 'docs/attribution.md'
  - 'Data Sources': 'docs/data-sources.md'
  - 'Layers': 'docs/layers.md'
  
# Extra variables for templates
extra:
  site_subtitle: 'Add open geospatial data to your applications with the vector tile map service.'
  project_repo_url: https://github.com/mapzen/vector-datasource
  docs_base_url: https://github.com/mapzen/vector-datasource/tree/master/docs
  exclude_home_contents_in_toc: false
